version: "3.2"

services:
  dev:
    container_name: kumandra-node-template
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/kumandra-node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/kumandra-node-template/.cargo
    volumes:
      - .:/var/www/kumandra-node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/kumandra-node-template --dev --ws-external"
